services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: database_development
    ports:
      - "3307:3306"  
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  adminer:
    image: adminer:4
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
