version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: hw13_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
